import React from 'react';
import Bingo from "./components/bingo";

let cognitiveFunctions = [
  {
    name: "te",
    questions: [
      "Rule follower",
      "Loves To-Do lists",
      "Appreciates structure and routine",
      "Sees the world in black and white",
      "Excels at planning",
      "Keeps the enviroment/workplace tidy and neat",
      "Judgemental of illogical decisions",
      "Quickly jumps to conclusions",
      "Finds satisfaction in organization",
      "Natural delegator",
      "Objective with defined goals",
      "Always prepared/has a plan b",
      "Often bossy",
      "Prone to being a workaholic",
      "Minimal procrastination",
      "Trusts authoratative sources",
      "Justice > Mercy",
      "Impatient with incompetent people",
      "Pride in honed skills",
      "Blunt",
      "Excels at leadership",
      "Likes systems dealing with variable interaction (math, physics, etc.)",
      "Overachiever",
      "Decisive",
      "Empircist"
     ],
    score: 0
  },
  {
    name: "ti",
    questions: [
      "Cynical of empirics",
      "Enjoys something stem",
      "often questioning, 'But what even is ___ anyway??'",
      "Likes debateing",
      "Enjoys puzzles/ mental challenges",
      "Gives practical solutions to emotional problems",
      "Does not mind being devil's advocate",
      "Knowledge for its own sake, application is afterthought",
      "Values meaning and purpose",
      "Prone to nihilism",
      "Needs a lot of time to think alone",
      "Expects reality to conform to their already existing ideas",
      "has internal belief systems built on past discoveries and insights",
      "Extremely independent",
      "Mind more organized than surroundings",
      "not opinionated, had few strong opinions",
      "Deconstructs and categorizes everything",
      "Favors sarcasm, satire and witty quips",
      "Adaptable troubleshooter",
      "Tends to be indecisive",
      "Tries to be unbiased/objective",
      "Easily recognizes logiacl incosistency/loopholes",
      "Competitive with oneself rather than others",
      "Rarely vocalizes thoughts behind a decision",
      "Precise speech, dislikes generalizations"
     ],
    score: 0
  },
  {
    name: "se",
    questions: [
      "Observes details without connecting it to past/future events",
      "Learns quickly from experience",
      "Recognizes physical opportunities when they see them, like an opening while playing football",
      "Not afraid of risks",
      "Spontaneous/impulsive",
      "Humor is based on delivery + practical jokes",
      "Hates being controlled by others",
      "Realist",
      "Lives in the moment",
      "Skilled and attentive drivers",
      "Restless, always moving",
      "Attracted to the aesthetically pleasing",
      "Great at handling emergencies",
      "Fast reflexes",
      "Easily adapts to new situations",
      "Adrenaline junkie",
      "Frequently goes to movies/ concerts/ events",
      "Focuses on the 5 senses (sight, smell, etc.)",
      "Notices things in their enviroment nobody else does",
      "Commitment issues",
      "Rarely clumsy",
      "Prefers engaging activities over conversing when hanging out",
      "Life of the party",
      "Prefers hands-on learning",
      "Rarely in their head"
     ],
    score: 0
  },
  {
    name: "si",
    questions: [
      "Rule follower",
      "Loves To-Do lists",
      "Appreciates structure and routine",
      "Sees the world in black and white",
      "Excels at planning",
      "Keeps the enviroment/workplace tidy and neat",
      "Judgemental of illogical decisions",
      "Quickly jumps to conclusions",
      "Finds satisfaction in organization",
      "Natural delegator",
      "Objective with defined goals",
      "Always prepared/has a plan b",
      "Often bossy",
      "Prone to being a workaholic",
      "Minimal procrastination",
      "Trusts authoratative sources",
      "Justice > Mercy",
      "Impatient with incompetent people",
      "Pride in honed skills",
      "Blunt",
      "Excels at leadership",
      "Likes systems dealing with variable interaction (math, physics, etc.)",
      "Overachiever",
      "Decisive",
      "Empircist"
     ],
    score: 0
  },
  {
    name: "ne",
    questions: [
      "Rule follower",
      "Loves To-Do lists",
      "Appreciates structure and routine",
      "Sees the world in black and white",
      "Excels at planning",
      "Keeps the enviroment/workplace tidy and neat",
      "Judgemental of illogical decisions",
      "Quickly jumps to conclusions",
      "Finds satisfaction in organization",
      "Natural delegator",
      "Objective with defined goals",
      "Always prepared/has a plan b",
      "Often bossy",
      "Prone to being a workaholic",
      "Minimal procrastination",
      "Trusts authoratative sources",
      "Justice > Mercy",
      "Impatient with incompetent people",
      "Pride in honed skills",
      "Blunt",
      "Excels at leadership",
      "Likes systems dealing with variable interaction (math, physics, etc.)",
      "Overachiever",
      "Decisive",
      "Empircist"
     ],
    score: 0
  },
  {
    name: "ni",
    questions: [
      "Rule follower",
      "Loves To-Do lists",
      "Appreciates structure and routine",
      "Sees the world in black and white",
      "Excels at planning",
      "Keeps the enviroment/workplace tidy and neat",
      "Judgemental of illogical decisions",
      "Quickly jumps to conclusions",
      "Finds satisfaction in organization",
      "Natural delegator",
      "Objective with defined goals",
      "Always prepared/has a plan b",
      "Often bossy",
      "Prone to being a workaholic",
      "Minimal procrastination",
      "Trusts authoratative sources",
      "Justice > Mercy",
      "Impatient with incompetent people",
      "Pride in honed skills",
      "Blunt",
      "Excels at leadership",
      "Likes systems dealing with variable interaction (math, physics, etc.)",
      "Overachiever",
      "Decisive",
      "Empircist"
     ],
    score: 0
  },
  {
    name: "fe",
    questions: [
      "Rule follower",
      "Loves To-Do lists",
      "Appreciates structure and routine",
      "Sees the world in black and white",
      "Excels at planning",
      "Keeps the enviroment/workplace tidy and neat",
      "Judgemental of illogical decisions",
      "Quickly jumps to conclusions",
      "Finds satisfaction in organization",
      "Natural delegator",
      "Objective with defined goals",
      "Always prepared/has a plan b",
      "Often bossy",
      "Prone to being a workaholic",
      "Minimal procrastination",
      "Trusts authoratative sources",
      "Justice > Mercy",
      "Impatient with incompetent people",
      "Pride in honed skills",
      "Blunt",
      "Excels at leadership",
      "Likes systems dealing with variable interaction (math, physics, etc.)",
      "Overachiever",
      "Decisive",
      "Empircist"
     ],
    score: 0
  },
  {
    name: "fi",
    questions: [
      "Rule follower",
      "Loves To-Do lists",
      "Appreciates structure and routine",
      "Sees the world in black and white",
      "Excels at planning",
      "Keeps the enviroment/workplace tidy and neat",
      "Judgemental of illogical decisions",
      "Quickly jumps to conclusions",
      "Finds satisfaction in organization",
      "Natural delegator",
      "Objective with defined goals",
      "Always prepared/has a plan b",
      "Often bossy",
      "Prone to being a workaholic",
      "Minimal procrastination",
      "Trusts authoratative sources",
      "Justice > Mercy",
      "Impatient with incompetent people",
      "Pride in honed skills",
      "Blunt",
      "Excels at leadership",
      "Likes systems dealing with variable interaction (math, physics, etc.)",
      "Overachiever",
      "Decisive",
      "Empircist"
     ],
    score: 0
  }
];
function App() {
  return (
  <div className="App">
    <Bingo cognitiveFunction = {cognitiveFunctions[0]} />
  </div>
  );
}

export default App;
