let cognitiveFunctions = [
    {
      name: "te",
      questions: [
        "Rule follower",
        "Loves To-Do lists",
        "Appreciates structure and routine",
        "Sees the world in black and white",
        "Excels at planning",
        "Keeps the enviroment/workplace tidy and neat",
        "Judgemental of illogical decisions",
        "Quickly jumps to conclusions",
        "Finds satisfaction in organization",
        "Natural delegator",
        "Objective with defined goals",
        "Always prepared/has a plan b",
        "Often bossy",
        "Prone to being a workaholic",
        "Minimal procrastination",
        "Trusts authoratative sources",
        "Justice > Mercy",
        "Impatient with incompetent people",
        "Pride in honed skills",
        "Blunt",
        "Excels at leadership",
        "Likes systems dealing with variable interaction (math, physics, etc.)",
        "Overachiever",
        "Decisive",
        "Empircist"
       ],
      score: 0
    },
    {
      name: "ti",
      questions: [
        "Cynical of empirics",
        "Enjoys something stem",
        "often questioning, 'But what even is ___ anyway??'",
        "Likes debateing",
        "Enjoys puzzles/ mental challenges",
        "Gives practical solutions to emotional problems",
        "Does not mind being devil's advocate",
        "Knowledge for its own sake, application is afterthought",
        "Values meaning and purpose",
        "Prone to nihilism",
        "Needs a lot of time to think alone",
        "Expects reality to conform to their already existing ideas",
        "has internal belief systems built on past discoveries and insights",
        "Extremely independent",
        "Mind more organized than surroundings",
        "not opinionated, had few strong opinions",
        "Deconstructs and categorizes everything",
        "Favors sarcasm, satire and witty quips",
        "Adaptable troubleshooter",
        "Tends to be indecisive",
        "Tries to be unbiased/objective",
        "Easily recognizes logiacl incosistency/loopholes",
        "Competitive with oneself rather than others",
        "Rarely vocalizes thoughts behind a decision",
        "Precise speech, dislikes generalizations"
       ],
      score: 0
    },
    {
      name: "se",
      questions: [
        "Observes details without connecting it to past/future events",
        "Learns quickly from experience",
        "Recognizes physical opportunities when they see them, like an opening while playing football",
        "Not afraid of risks",
        "Spontaneous/impulsive",
        "Humor is based on delivery + practical jokes",
        "Hates being controlled by others",
        "Realist",
        "Lives in the moment",
        "Skilled and attentive drivers",
        "Restless, always moving",
        "Attracted to the aesthetically pleasing",
        "Great at handling emergencies",
        "Fast reflexes",
        "Easily adapts to new situations",
        "Adrenaline junkie",
        "Frequently goes to movies/ concerts/ events",
        "Focuses on the 5 senses (sight, smell, etc.)",
        "Notices things in their enviroment nobody else does",
        "Commitment issues",
        "Rarely clumsy",
        "Prefers engaging activities over conversing when hanging out",
        "Life of the party",
        "Prefers hands-on learning",
        "Rarely in their head"
       ],
      score: 0
    },
    {
      name: "si",
      questions: [
        "Appreciates cultural traditions",
        "Sticks with tried and tru methods",
        "Excellent memory",
        "Never makes the same mistake twice",
        "Acutely aware of their level of thirst, hunger, etc.",
        "Wakes up and goes to bed around the same time everyday",
        "Actively tries to maintain health",
        "Loves to reminisce on the past",
        "Stubborn",
        "Dislikes inconsistent people",
        "Details > big-picture",
        "Values security and stability",
        "Excels at carefully following procedures",
        "Worst thing you can do is abuse their trust",
        "Knows more details about others than they do about themselves",
        "Follows a schedule/ routine",
        "Conscious of the fleeting nature of the present",
        "Only cares about ideas with real world applications",
        "Trusts their experience over everything",
        "Cracks jokes about making observations about others",
        "Catches onto lies easily",
        "Punctual",
        "Immediately notices if someone changed something about their apprearances",
        "Dependable",
        "I enjoy organizing and categorizing information"
       ],
      score: 0
    },
    {
      name: "ne",
      questions: [
        "Entrepreneurial spirit",
        "described as weird or quirky",
        "creative",
        "can always entertain themselves",
        "Can get along with anyone",
        "Hyperfocused when they are inspired",
        "readily accepts change",
        "great at ideating in a group",
        "Naturally curious",
        "always working on a side project",
        "open-minded",
        "many casual hobbies they drop and pick up at will",
        "makes connections between seemingly unrelated topics",
        "Difficulty with commitment",
        "Unconventional problem solver",
        "Quick witted",
        "childlike excitement",
        "Spontaneous bursts of energy",
        "jack of all trades",
        "has many ideas but rarely acts on them",
        "struggles with picking just one career",
        "abstract is more interesting than concrete",
        "extremely curious and eager to learn about variety of topics",
        "enjoys imagining different scenarios and outcomes",
        "i enjoy exploring multiple options"
       ],
      score: 0
    },
    {
      name: "ni",
      questions: [
        "big picture > minor details",
        "drawn to history/ humanities",
        "answers questions slowely and carefully",
        "easily spots trends in behaviour/ events",
        "speaks in sentences t=rather than conjectures",
        "uses metaphors and abstract concepts when speaking",
        "sudden realizations, eureka moments",
        "drawn to symbolism",
        "future oriented",
        "hard to fool",
        "private guarded",
        "often offers new and unique insights",
        "difficulty explaining perceptions verbally",
        "Constantly looking towards improvement",
        "distrusts first impressions",
        "distrusts first impressions",
        "needs a particular enviroment to properly process info",
        "purposeful experimentation > tried and true",
        "skilled at preparing strategies to reach goals",
        "thinks in images/impressions rather than words/ sentences",
        "arruned to 'gut-feelings'",
        "enjoys envisioning their life's trajectory",
        "Reflective",
        "I 'go with the flow'",
        "i fail to explain my thought process"
       ],
      score: 0
    },
    {
      name: "fe",
      questions: [
        "understand how to manipulate even if they wont",
        "priotitizes other's needs",
        "easily recognizes if something is socially appropriate",
        "emotionally supportive",
        "defers to popular opinion",
        "uses jokes to diffuse another person's embarrasesment",
        "can readily change the 'mood'",
        "can discern others' motives accurately",
        "Extremely empathetic",
        "Excellent manners",
        "naturally aware of social hierarchy (outcasts, leaders, etc.)",
        "prone to shame",
        "highly motivated by criticism/praise",
        "honers social obligations",
        "hard to process feelings without speaking to someone",
        "many friends and acquaintances",
        "warm with people",
        "likes volunteer work",
        "others may percieve them as fake or 'posers'",
        "acutely aware of how decisions impact others",
        "feels responsible for others' emotions",
        "values group morale",
        "passive aggressive > aggressive",
        "conflict makes them feel uneasy",
        "i am great at mediating conflicts"
       ],
      score: 0
    },
    {
      name: "fi",
      questions: [
        "genuine awkwardness >> smooth insincerity",
        "morally aware",
        "hates critiquing others",
        "mostly easygoing but 10% stubborn as hell",
        "has a pet cause",
        "kind but dislikes social niceties",
        "innocent charm",
        "marches to the beat of their own drum",
        "only cries in private",
        "craves freedom",
        "shows few people their music/art",
        "hides their intents and personal values",
        "organizes playlists by mood",
        "prone to guilt",
        "vegan or wants to be vegan because of moral justification",
        "seems like a people pleaser at first glance",
        "fantastic active listener",
        "has gut feelings about right and wrong",
        "easily spots fakers",
        "live and let live",
        "i do what i feel is right regardless of what society tells me",
        "chronic daydreamer",
        "seeks inner harmony",
        "their face betrays attempts to hide emotions",
        "values meaningful close relationships based on mutual understanding"
       ],
      score: 0
    }
  ];

  export default cognitiveFunctions;