let jobs = [
    {
        name: "Software Engineer",
        ti: 25,
        te: 25,
        ni: 10,
        ne: 15,
        si: 15,
        se: 0,
        fi: 0,
        fe: 10,
        score: 100,
    },
    {
        name: "Front-End Developer",
        ti: 5,
        te: 10,
        ni: 5,
        ne: 20,
        si: 10,
        se: 20,
        fi: 0,
        fe: 30,
        score: 100,
    },
    {
        name: "Back-End Developer",
        ti: 25,
        te: 30,
        ni: 10,
        ne: 10,
        si: 15,
        se: 5,
        fi: 0,
        fe: 5,
        score: 100,
    },
    {
        name: "Full-Stack Developer",
        ti: 15,
        te: 20,
        ni: 10,
        ne: 20,
        si: 5,
        se: 15,
        fi: 0,
        fe: 15,
        score: 100,
    },
    {
        name: "Mobile App Developer",
        ti: 15,
        te: 20,
        ni: 10,
        ne: 10,
        si: 10,
        se: 15,
        fi: 0,
        fe: 20,
        score: 100,
    },
    {
        name: "Game Developer",
        ti: 10,
        te: 15,
        ni: 5,
        ne: 15,
        si: 10,
        se: 25,
        fi: 0,
        fe: 20,
        score: 100,
    },
    {
        name: "DevOps Engineer",
        ti: 15,
        te: 20,
        ni: 10,
        ne: 10,
        si: 30,
        se: 10,
        fi: 0,
        fe: 5,
        score: 100,
    },
    {
        name: "Firmware Engineer",
        ti: 15,
        te: 20,
        ni: 15,
        ne: 5,
        si: 25,
        se: 10,
        fi: 0,
        fe: 10,
        score: 100,
    },
    {
        name: "Embedded Systems Engineer",
        ti: 25,
        te: 25,
        ni: 15,
        ne: 5,
        si: 20,
        se: 5,
        fi: 0,
        fe: 5,
        score: 100,
    },
    {
        name: "Software Architect",
        ti: 23,
        te: 25,
        ni: 10,
        ne: 12,
        si: 15,
        se: 5,
        fi: 0,
        fe: 10,
        score: 100,
    },
    {
        name: "Application Support Engineer",
        ti: 25,
        te: 15,
        ni: 5,
        ne: 10,
        si: 15,
        se: 5,
        fi: 0,
        fe: 25,
        score: 100,
    },
    {
        name: "AI/ML Engineer",
        ti: 30,
        te: 15,
        ni: 20,
        ne: 20,
        si: 10,
        se: 5,
        fi: 0,
        fe: 0,
        score: 100,
    },
    {
        name: "Cloud Computing Specialist",
        ti: 20,
        te: 15,
        ni: 10,
        ne: 20,
        si: 25,
        se: 10,
        fi: 0,
        fe: 0,
        score: 100,
    },
    {
        name: "IT Manager",
        ti: 15,
        te: 30,
        ni: 10,
        ne: 10,
        si: 10,
        se: 5,
        fi: 0,
        fe: 20,
        score: 100,
    },
    {
        name: "UI/UX Designer",
        ti: 5,
        te: 10,
        ni: 5,
        ne: 15,
        si: 20,
        se: 15,
        fi: 0,
        fe: 30,
        score: 100,
    },
    {
        name: "Data engineer",
        ti: 15,
        te: 25,
        ni: 10,
        ne: 10,
        si: 30,
        se: 5,
        fi: 0,
        fe: 5,
        score: 100,
    },
    {
        name: "Data scientist",
        ti: 30,
        te: 15,
        ni: 10,
        ne: 25,
        si: 10,
        se: 5,
        fi: 0,
        fe: 5,
        score: 100,
    },
    {
        name: "Data analyst",
        ti: 30,
        te: 20,
        ni: 10,
        ne: 15,
        si: 15,
        se: 0,
        fi: 0,
        fe: 10,
        score: 100,
    }
];

export default jobs;
